---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: msite1-libvirt-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: libvirt-global
      component: libvirt
    actions:
      - method: replace
        path: .values
      - method: merge
        path: .
  storagePolicy: cleartext
data:
#  chart_name: msite1-libvirt
#  release: msite1-libvirt
#  namespace: msite1
  chart_name: libvirt
  release: libvirt
  namespace: openstack
  wait:
    timeout: 300
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
#            release_group: msite1-airship-libvirt
            release_group: airship-libvirt
  values:
    labels:
      agent:
        libvirt:
          node_selector_key: openstack-compute-node
          node_selector_value: enabled
    conf:
      ceph:
        enabled: false
...
