---
- name: Defined servers
  hosts: localhost
  vars:
    k8s_hosts:
      k8s_contr:
        - k8s_contr_1
      k8s_minion:
        - k8s_minion_1
        - k8s_minion_2
  tasks:
    - name: Info about defined hosts
      debug:
        var: k8s_hosts

    - name: Set k8s_hosts as fact
      set_fact:
        k8s_hosts: "{{ k8s_hosts }}"
