---
- name: display contr hosts
  debug:
    msg: "{{ k8s_hosts['k8s_contr'] }}"

- name: display minions hosts
  debug:
    msg: "{{ k8s_hosts['k8s_minion'] }}"

- name: "Getting info about k8s_contr if exist"
  os_server_facts:
    auth:
      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      username: "{{ lookup('env', 'OS_USERNAME') }}"
      password: "{{ lookup('env', 'OS_PASSWORD') }}"
      project_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
      user_domain_name: "{{ lookup('env', 'OS_USER_DOMAIN_NAME') }}"
      project_domain_name: "{{ lookup('env', 'OS_PROJECT_DOMAIN_NAME') }}"
    region_name: "{{ lookup('env', 'OS_REGION_NAME') }}"
    server: "{{ server_name }}"
  with_items: "{{ k8s_hosts['k8s_contr'] }}"
  loop_control:
    loop_var: server_name
  register: k8s_contr_result

- name: display contr hosts
  debug:
    var: k8s_contr_result

- when: k8s_contr_result.results[0].ansible_facts.openstack_servers != []
  name: Add contr into inventory
  add_host:
     name: "{{ item.public_v4 }}"
     group: k8s_contr
  with_items: "{{ k8s_contr_result.results[0].ansible_facts.openstack_servers }}"

- name: "Getting info about k8s_minion if exist"
  os_server_facts:
    auth:
      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      username: "{{ lookup('env', 'OS_USERNAME') }}"
      password: "{{ lookup('env', 'OS_PASSWORD') }}"
      project_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
      user_domain_name: "{{ lookup('env', 'OS_USER_DOMAIN_NAME') }}"
      project_domain_name: "{{ lookup('env', 'OS_PROJECT_DOMAIN_NAME') }}"
    region_name: "{{ lookup('env', 'OS_REGION_NAME') }}"
    server: "{{ server_name }}"
  with_items: "{{ k8s_hosts['k8s_minion'] }}"
  loop_control:
    loop_var: server_name
  register: k8s_minion_result

- name: display minion hosts
  debug:
    var: k8s_minion_result

- when: k8s_minion_result.results[0].ansible_facts.openstack_servers != []
  name: Add minions into inventory
  add_host:
     name: "{{ item.public_v4 }}"
     group: k8s_minion
  with_items: "{{ k8s_minion_result.results[1].ansible_facts.openstack_servers }}"
