---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-rabbitmq
  replacement: true
  labels:
    name: openstack-rabbitmq-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: openstack-rabbitmq-global
    actions:
      - method: delete
        path: .values.labels.prometheus_rabbitmq_exporter
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  chart_name: {{ namespace }}-rabbitmq
  release: {{ namespace }}-rabbitmq
  namespace: {{ namespace }}
  wait:
    timeout: 900
    labels:
      release_group: airship-{{ namespace }}-rabbitmq
    resources:
      - type: statefulset
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-{{ namespace }}-rabbitmq
  test:
    enabled: false
  values:
    pod:
      replicas:
        server: 3
    monitoring:
      prometheus:
        enabled: false
...
