---
- name: Prepare hosts
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa_ansible
  tasks:
      # temporary workaround
    - name: Check if openrc file exist
      stat:
        path: /home/ubuntu/openrc
      register: openrc_file

    - when: openrc_file.stat.exists == True
      name: Run mariaDB rabbitMQ memcached on k8s_contr
      become: true
      become_user: ubuntu
      shell: |
        set timeout 300
        cd /opt/openstack-helm
        nohup ./tools/deployment/multinode/050-mariadb.sh &
        nohup ./tools/deployment/multinode/060-rabbitmq.sh &
        nohup ./tools/deployment/multinode/070-memcached.sh &
        wait
      environment:
        OSH_EXTRA_HELM_ARGS: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS') }}"
        OSH_EXTRA_HELM_ARGS_MARIADB: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_MARIADB') }}"
        OSH_EXTRA_HELM_ARGS_RABBITMQ: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_RABBITMQ') }}"
        OSH_EXTRA_HELM_ARGS_MEMCACHED: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_MEMCACHED') }}"
      delegate_to: "{{ groups['k8s_contr'][0] }}"
      ignore_errors: yes
      register: basic_services_result
      run_once: True

    ###########################################################################
    - when: "{{ lookup('env', 'OS_DEPLOY_ALL') | default(true) | bool }}"
      name: Run Keystone, RadosGW, Cinder, Glance on k8s_contr
      become: true
      become_user: ubuntu
      shell: |
        set timeout 300
        cd /opt/openstack-helm
        export GLANCE_BACKEND=rbd
        nohup ./tools/deployment/multinode/080-keystone.sh &
        nohup ./tools/deployment/multinode/090-ceph-radosgateway.sh &
        nohup ./tools/deployment/multinode/100-glance.sh &
        nohup ./tools/deployment/multinode/110-cinder.sh &
        wait
      environment:
        OSH_EXTRA_HELM_ARGS: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS') }}"
        OSH_EXTRA_HELM_ARGS_KEYSTONE: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_KEYSTONE') }}"
        OSH_EXTRA_HELM_ARGS_HEAT: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_HEAT') }}"
        OSH_EXTRA_HELM_ARGS_GLANCE: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_GLANCE') }}"
        OSH_EXTRA_HELM_ARGS_CINDER: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_CINDER') }}"
      delegate_to: "{{ groups['k8s_contr'][0] }}"
      ignore_errors: yes
      register: os_services_result
      run_once: True

    - when: "{{ lookup('env', 'OS_DEPLOY_ALL') | default(true) | bool }}"
      name: Run Heat, Barbican and tempest on k8s_contr
      become: true
      become_user: ubuntu
      shell: |
        set timeout 300
        cd /opt/openstack-helm
        export GLANCE_BACKEND=rbd
        nohup ./tools/deployment/multinode/150-heat.sh &
        nohup ./tools/deployment/multinode/160-barbican.sh &
        #        nohup ./tools/deployment/multinode/900-tempest.sh &
        wait
      environment:
        OSH_EXTRA_HELM_ARGS: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS') }}"
        OSH_EXTRA_HELM_ARGS_HEAT: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_HEAT') }}"
        OSH_EXTRA_HELM_ARGS_BARBICAN: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_BARBICAN') }}"
        #        OSH_EXTRA_HELM_ARGS_TEMPEST: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_TEMPEST') }}"
      delegate_to: "{{ groups['k8s_contr'][0] }}"
      ignore_errors: yes
      register: os_services_result
      run_once: True

    - when: "{{ lookup('env', 'OS_DEPLOY_ALL') | default(true) | bool }} and (os_services_result | success)"
      name: Configure minions to use OVS and libvirt
      become: true
      become_user: ubuntu
      shell: |
        set timeout 300
        cd /opt/openstack-helm
        nohup ./tools/deployment/multinode/140-compute-kit.sh &
        nohup ./tools/deployment/multinode/120-openvswitch.sh &
        nohup ./tools/deployment/multinode/130-libvirt.sh &
        wait
      environment:
        OSH_EXTRA_HELM_ARGS: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS') }}"
        OSH_EXTRA_HELM_ARGS_NOVA: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_NOVA') }}"
        OSH_EXTRA_HELM_ARGS_NEUTRON: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_NEUTRON') }}"
        OSH_EXTRA_HELM_ARGS_OPENVSWITCH: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_OPENVSWITCH') }}"
        OSH_EXTRA_HELM_ARGS_LIBVIRT: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_LIBVIRT') }}"
      delegate_to: "{{ groups['k8s_contr'][0] }}"
      ignore_errors: yes
      register: os_compute_result
      run_once: True
