---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: full-site
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: full-site-global
    actions:
      - method: replace
        path: .chart_groups
  storagePolicy: cleartext
data:
  release_prefix: airship
  chart_groups:
    - openstack-ingress-controller-airskiff
    - openstack-mariadb-airskiff
    - openstack-memcached-airskiff
    - openstack-rabbitmq-airskiff
    - openstack-keystone-airskiff
    - openstack-glance-airskiff
    - openstack-compute-kit-airskiff
  namespace: mynewnamespace
...
