---
- name: Change sudoers
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: ".ssh/id_rsa_ansible"
  tasks:
    - name: Clone treasuremap repo
      shell: |
        git clone https://opendev.org/airship/treasuremap.git treasuremap | tee -a logs
      ignore_errors: true
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"
