---
- name: Do post treasuremap things
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: 100-deploy-osh.sh
      sudo: yes
      sudo_user: ubuntu
      shell: |
        cd treasuremap && \
        sudo  ./tools/deployment/airskiff/developer/100-deploy-osh.sh >> /home/ubuntu/logs 2>&1
      ignore_errors: yes
      run_once: true
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"
