---
- name: Do post treasuremap things
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: ".ssh/id_rsa_ansible"
  tasks:
    - name: 000-install-packages.sh
      sudo: yes
      sudo_user: ubuntu
      shell: |
        cd treasuremap && \
        ./tools/deployment/airskiff/developer/000-install-packages.sh | tee -a logs
      ignore_errors: true
      run_once: True

    - name: 005-clone-dependencies.sh
      sudo: yes
      sudo_user: ubuntu
      shell: |
        cd treasuremap && \
         ./tools/deployment/airskiff/developer/005-clone-dependencies.sh | tee -a logs
      ignore_errors: true
      run_once: true

    - name: 020-setup-client.sh
      sudo: yes
      sudo_user: ubuntu
      shell: |
        cd treasuremap && \
        sudo  ./tools/deployment/airskiff/developer/020-setup-client.sh | tee -a logs
      ignore_errors: yes
      run_once: true
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"

    - name: change ownership of airskiff.yaml
      sudo: yes
      sudo_user: ubuntu
      shell: |
        if [ ! -f treasuremap/airskiff.yaml ]; then
          touch treasuremap/airskiff.yaml
        fi
        sudo chmod 0644 treasuremap/airskiff.yaml
      ignore_errors: true
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"

    - name: 030-armada-bootstrap.sh
      sudo: yes
      sudo_user: ubuntu
      shell: |
        cd treasuremap && \
        sudo ./tools/deployment/airskiff/developer/030-armada-bootstrap.sh | tee -a logs
      ignore_errors: yes
      run_once: true
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"

    - name: Setup openrc
      shell: |
        export OS_PASSWORD=$(grep 'password' treasuremap/site/airskiff/secrets/passphrases/osh_keystone_admin_password.yaml | grep data | awk '{print $2}')
        bash scripts/set-openrc.sh
      ignore_errors: yes
      run_once: true
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"
