---
- name: Prepare hosts
  hosts:
    - k8s_contr
    - k8s_minion
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: "Accept traffic on minions to k8s_contr"
      iptables:
        chain: INPUT
        protocol: tcp
        source: "{{ groups['k8s_contr'] | join(',') }}"
        destination_port: '22'
        jump: ACCEPT
        action: insert
      run_once: True

    - name: Upgrade minion
      sudo: yes
      sudo_user: ubuntu
      shell: /bin/bash -x /home/ubuntu/upgrade-host.sh >> /home/ubuntu/logs
      register: upgrade_status
      ignore_errors: yes
      run_once: True

    - name: add bash completion
      shell: |
        echo "source <(kubectl completion bash)" >> /home/ubuntu/.bashrc
        echo "alias k=kubectl" >> /home/ubuntu/.bashrc
        echo "complete -F __start_kubectl k" >> /home/ubuntu/.bashrc
      ignore_errors: yes
      run_once: true
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"

    - name: remove nano
      sudo: yes
      sudo_user: ubuntu
      shell: /usr/bin/sudo /usr/bin/apt remove -y nano
      ignore_errors: true

    - name: install other packages
      sudo: yes
      sudo_user: ubuntu
      shell: /usr/bin/sudo /usr/bin/apt install -y vim htop ccze
      ignore_errors: true
