---
- block:
  - name: Create log dir if not present
    sudo: yes
    sudo_user: ubuntu
    shell: |
      mkdir -p logs

  # FIXME: add new iptabls rules
  - name: "Accept traffic on minions to k8s_contr"
    iptables:
      chain: INPUT
      protocol: tcp
      source: "{{ groups['k8s_contr'] | join(',') }}"
      destination_port: '22'
      jump: ACCEPT
      action: insert

  - name: Upgrade hosts
    sudo: yes
    sudo_user: ubuntu
    shell: |
      bash -x scripts/upgrade-host.sh 2>&1 | tee -a "logs/cluster-logs-{{ ansible_nodename }}-{{ namespace }}"
    ignore_errors: yes

  - name: remove nano
    apt:
      name: nano
      state: absent

  - name: install other packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - vim
      - htop
      - ccze

  - when: not setup_minikube
    name: Install NFS common package
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - nfs-common
      - python-wheel

- name: Change owner to Ubuntu for opt dir
  become: true
  become_user: ubuntu
  shell: |
    sudo chown -R ubuntu:ubuntu /opt
  ignore_errors: True
