---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: mynamespace-libvirt
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: libvirt-global
      component: libvirt
    actions:
      - method: replace
        path: .values
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  chart_name: mynamespace-libvirt
  release: mynamespace-libvirt
  namespace: mynamespace
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-mynamespace-libvirt
  values:
    labels:
      agent:
        libvirt:
          node_selector_key: openstack-compute-node
          node_selector_value: enabled
    conf:
      ceph:
        enabled: false
...
