---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: mynamespace-neutron
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: neutron-global
      component: neutron
    actions:
      - method: merge
        path: .
      - method: replace
        path: .values.labels.agent.l3
      - method: replace
        path: .values.network
      - method: replace
        path: .values.conf.neutron
      - method: replace
        path: .values.conf.plugins
      - method: replace
        path: .values.conf.auto_bridge_add.br-ex
  storagePolicy: cleartext
data:
  chart_name: mynamespace-neutron
  release: mynamespace-neutron
  namespace: mynamespace
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-mynamespace-neutron
  wait:
    timeout: 900
    labels:
      release_group: airship-mynamespace-neutron
  values:
    pod:
      replicas:
        server: 3
    labels:
      agent:
        l3:
          node_selector_key: openstack-control-plane
          node_selector_value: enabled
    network:
      interface:
        tunnel: docker0
    conf:
      neutron:
        DEFAULT:
          l3_ha: False
          max_l3_agents_per_router: 1
          l3_ha_network_type: vxlan
          dhcp_agents_per_network: 1
      plugins:
        ml2_conf:
          ml2_type_flat:
            flat_networks: public
        openvswitch_agent:
          agent:
            tunnel_types: vxlan
          ovs:
            bridge_mappings: public:br-ex
        linuxbridge_agent:
          linux_bridge:
            bridge_mappings: public:br-ex
      auto_bridge_add:
        br-ex: docker0
...
