---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: mynamespace-openvswitch
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openvswitch-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  chart_name: mynamespace-openvswitch
  release: mynamespace-openvswitch
  namespace: mynamespace
  wait:
    timeout: 900
    labels:
      release_group: airship-mynamespace-openvswitch
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-mynamespace-openvswitch
...
