---
- name: Prepare hosts
  hosts:
    - airship_contr
    - airship_minion
  serial:
    - "100%"
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: "Copy controller script"
      copy:
        src: /home/ubuntu/openstack-helm-deployment/scripts/setup-armada-controller.sh
        dest: /home/ubuntu/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['airship_contr'] }}"

    - name: "Copy controller script"
      copy:
        src: /home/ubuntu/openstack-helm-deployment/scripts/clone-osh-repo.sh
        dest: /home/ubuntu/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['airship_contr'] }}"

    - name: "Copy minion script"
      copy:
        src: /home/ubuntu/openstack-helm-deployment/scripts/setup-new-host.sh
        dest: /home/ubuntu/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['airship_minion'] }}"

    - name: "Copy controller script"
      copy:
        src: /home/ubuntu/openstack-helm-deployment/scripts/upgrade-host.sh
        dest: /home/ubuntu/
        mode: 0755
        group: ubuntu
        owner: ubuntu

    - name: "Copy get pods script"
      copy:
        src: /home/ubuntu/openstack-helm-deployment/scripts/get-pods.sh
        dest: /home/ubuntu/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['airship_contr'] }}"
