---
- when: repo_name and repo_login and repo_password
  sudo: yes
  sudo_user: ubuntu
  shell: |
    docker login "{{ repo_name }}" -u "{{ repo_login }}" -p"{{ repo_password }}"
  ignore_errors: false

- when: not repo_name and not repo_login and not repo_password
  sudo: yes
  sudo_user: ubuntu
  synchronize:
    src: docker/
    dest: .docker/

- name: Restart docker service
  service:
    name: docker
    state: restarted
