---
- name: Copy kubernetes install script
  hosts: localhost
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: ".ssh/id_rsa_ansible"
    setup_minikube: "{{ true if lookup('env', 'SETUP_MINIKUBE') == 'true' else false }}"
  tasks:
    - when: not setup_minikube
      name: "Copy install-kubernetes script"
      sudo: yes
      sudo_user: ubuntu
      copy:
        src: "{{ ansible_env.OLDPWD }}/scripts/install-kubernetes.sh"
        dest: scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['all'] }}"

- name: Execute kubernetes install script
  hosts:
    - k8s_contr
    - k8s_minion
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: ".ssh/id_rsa_ansible"
    setup_minikube: "{{ true if lookup('env', 'SETUP_MINIKUBE') == 'true' else false }}"
  tasks:
    # FIXME: add SETUP_MINIKUBE
    - when: setup_minikube
      name: 010-deploy-k8s.sh
      sudo: yes
      sudo_user: ubuntu
      shell: |
        cd treasuremap && \
        ./tools/deployment/airskiff/developer/010-deploy-k8s.sh >> /home/ubuntu/logs 2>&1
      ignore_errors: true
      run_once: true
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"

    - when: not setup_minikube
      shell: |
        dpkg -l | grep -q kubeadm
      register: kubeadm_status

    - when: not setup_minikube and kubeadm_status.rc == 1
      name: Install kubernetes packages
      sudo: yes
      sudo_user: ubuntu
      shell: |
        bash -x scripts/install-kubernetes.sh >> /home/ubuntu/logs 2>&1
      ignore_errors: false
