---
- name: Change sudoers
  hosts:
    - k8s_contr
    - k8s_minion
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: "/home/ubuntu/.ssh/id_rsa_ansible"
    setup_minikube: "{{ true if lookup('env', 'SETUP_MINIKUBE') == 'true' else false }}"
  tasks:
    # FIXME: add SETUP_MINIKUBE
    - when: setup_minikube
      name: 010-deploy-k8s.sh
      sudo: yes
      sudo_user: ubuntu
      shell: |
        cd /home/ubuntu/treasuremap && \
         ./tools/deployment/airskiff/developer/010-deploy-k8s.sh >> /home/ubuntu/logs 2>&1
      ignore_errors: true
      run_once: true
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"

    - when: not setup_minikube
      name: "Copy install-kubernetes script"
      sudo: yes
      sudo_user: ubuntu
      copy:
        src: /home/ubuntu/openstack-helm-deployment/scripts/install-kubernetes.sh
        dest: /home/ubuntu/scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu

    - when: not setup_minikube
      name: Deploy k8s
      sudo: yes
      sudo_user: ubuntu
      shell: |
        bash -x /home/ubuntu/scripts/install-kubernetes.sh | tee -a /home/ubuntu/logs
      ignore_errors: false
