---
- name: Join minions into the k8s cluster
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: Join k8s host into the cluster
      shell: |
        bash -x scripts/join-node.sh "{{ item }}" | tee -a logs
      with_items: "{{ groups['k8s_minion'] }}"
