---
- name: Set k8s node labels
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    setup_minikube: "{{ true if lookup('env', 'SETUP_MINIKUBE') == 'true' else false }}"
  tasks:
    - when: not setup_minikube
      name: Set node labels
      sudo: yes
      sudo_user: ubuntu
      shell: |
        kubectl label nodes --all openstack-control-plane=enabled
        kubectl label nodes --all openstack-compute-node=enabled
        kubectl label nodes --all openvswitch=enabled
        kubectl label nodes --all linuxbridge=enabled
        kubectl label nodes --all ceph-mon=enabled
        kubectl label nodes --all ceph-osd=enabled
        kubectl label nodes --all ceph-mds=enabled
        kubectl label nodes --all ceph-rgw=enabled
        kubectl label nodes --all ceph-mgr=enabled
        # from 010-deploy-k8s.sh
        kubectl label nodes --all --overwrite ucp-control-plane=enabled
      ignore_errors: false
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"
