---
- name: Setup Kubernetes controller
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: ".ssh/id_rsa_ansible"
    setup_minikube: "{{ true if lookup('env', 'SETUP_MINIKUBE') == 'true' else false }}"
  tasks:
    - when: not setup_minikube
      name: Check if k8s controller has not been deployed earlier
      wait_for:
        host: "{{ groups['k8s_contr'][0] }}"
        port: "{{ item }}"
        state: started
        delay: 3
        timeout: 5
      ignore_errors: yes
      register: k8s_contr_status
      with_items:
        - 6443

    - when: not setup_minikube and k8s_contr_status
      name: Deploy k8s
      sudo: yes
      sudo_user: ubuntu
      shell: |
        bash -x scripts/install-kubernetes-controller.sh | tee -a logs
      ignore_errors: false

    - name: wait kubernetes to be ready
      wait_for:
        host: "{{ groups['k8s_contr'][0] }}"
        port: "{{ item }}"
        state: started
        delay: 30
        timeout: 301
      ignore_errors: yes
      with_items:
        - 6443
