---
- name: Change sudoers
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: "/home/ubuntu/.ssh/id_rsa_ansible"
    setup_minikube: "{{ true if lookup('env', 'SETUP_MINIKUBE') == 'true' else false }}"
  tasks:
    - when: not setup_minikube
      name: Deploy k8s
      sudo: yes
      sudo_user: ubuntu
      shell: |
        bash -x /home/ubuntu/scripts/install-kubernetes-controller.sh | tee -a /home/ubuntu/logs
      ignore_errors: false

    - name: wait kubernetes to be ready
      wait_for:
        host: "{{ groups['k8s_contr'][0] }}"
        port: "{{ item }}"
        state: started
        delay: 30
        timeout: 301
      ignore_errors: yes
      with_items:
        - 6443
