---
- name: Post actions for k8s
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: Add bash completion
      shell: |
        echo "source <(kubectl completion bash)" | tee -a .bashrc
        echo "alias k=kubectl" | tee -a .bashrc
        echo "complete -F __start_kubectl k" | tee -a .bashrc
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"
      ignore_errors: yes
      run_once: True
