---
- block:
  - when: "{{ lookup('env', 'ANSIBLE_HOST_KEY_CHECKING') }}"
    name: Add k8s_contr host key to known_hosts
    shell: ssh-keyscan -H "{{ item }}" | tee -a "${HOME}/.ssh/known_hosts"
    with_items: "{{ groups['k8s_contr'] }}"
    args:
      executable: /bin/bash

  - when: "{{ lookup('env', 'ANSIBLE_HOST_KEY_CHECKING') }}"
    name: Add k8s_minion host key to known_hosts
    shell: ssh-keyscan -H "{{ item }}" | tee -a "${HOME}/.ssh/known_hosts"
    with_items: "{{ groups['k8s_minion'] }}"
    args:
      executable: /bin/bash
