---
- name: Defined local inventory
  hosts: localhost
  vars:
    k8s_hosts:
      k8s_contr:
        - "{{ lookup('env', 'CONTR_NAME') if lookup('env', 'CONTR_NAME') != '' else 'bob_contr' }}"
      k8s_minion:
        # If you need more minion nodes, just add same entry
        - "{{ lookup('env', 'MINION_1_NAME') if lookup('env', 'MINION_1_NAME') != '' else 'stevard_minion'  }}"
        - "{{ lookup('env', 'MINION_2_NAME') if lookup('env', 'MINION_2_NAME') != '' else 'kevin_minion'  }}"
  tasks:
    - name: Info about defined hosts
      debug:
        var: k8s_hosts

    - name: Set k8s_hosts as fact
      set_fact:
        k8s_hosts: "{{ k8s_hosts }}"
        contr_flavor: b2-60
        contr_image: "Ubuntu 16.04"
        contr_key_name: ansible_key
        contr_net_name: Ext-Net
        minion_flavor: b2-60
        minion_image: "Ubuntu 16.04"
        minion_net_name: Ext-Net
        # Name of the docker registry that later ansible will pull images
        repo_name: docker.io
        openstack_keypair_name: "{{ lookup('env', 'OPENSTACK_KEYPAIR_NAME') if lookup('env', 'OPENSTACK_KEYPAIR_NAME') != '' else 'ansible_key'  }}"
        ansible_ssh_keyname: "{{ lookup('env', 'ANSIBLE_SSH_KEYNAME') if lookup('env', 'ANSIBLE_SSH_KEYNAME') != '' else 'id_rsa_ansible'  }}"
