---
- name: Defined local inventory
  hosts: localhost
  vars:
    k8s_hosts:
      k8s_contr:
        - "{{ lookup('env', 'CONTR_NAME') if lookup('env', 'CONTR_NAME') != '' else 'k8s_contr_1' }}"
      k8s_minion:
        # If you need more minion nodes, just add same entry
        - "{{ lookup('env', 'MINION_1') if lookup('env', 'MINION_1') != '' else 'k8s_minion_1'  }}"
  tasks:
    - name: Info about defined hosts
      debug:
        var: k8s_hosts

    - name: Set k8s_hosts as fact
      set_fact:
        k8s_hosts: "{{ k8s_hosts }}"
        contr_flavor: b2-30
        contr_image: "Ubuntu 16.04"
        contr_key_name: ansible_key
        contr_net_name: Ext-Net
        minion_flavor: b2-30
        minion_image: "Ubuntu 16.04"
        minion_key_name: ansible_key
        minion_net_name: Ext-Net
        ansible_ssh_keyname: "id_rsa_ansible"
        # Name of the docker registry that later ansible will pull images
        repo_name: docker.io
