---
- name: Defined facts for remote hosts
  hosts:
    - k8s_contr
    - k8s_minion
  vars:
  tasks:
    - name: Set facts to other hosts
      set_fact:
        # Name of the docker registry that later ansible will pull images
        repo_name: docker.io
        repo_dir: /home/ubuntu/openstack-helm-deployment
