---
- when: setup_airskiff
  block:
  - name: 000-install-packages.sh
    sudo: yes
    sudo_user: ubuntu
    shell: |
      cd treasuremap && \
      ./tools/deployment/airskiff/developer/000-install-packages.sh 2>&1 | tee -a /home/ubuntu/logs
    ignore_errors: true
    run_once: True

  - name: 005-clone-dependencies.sh
    sudo: yes
    sudo_user: ubuntu
    shell: |
      cd treasuremap && \
      ./tools/deployment/airskiff/developer/005-clone-dependencies.sh 2>&1 | tee -a /home/ubuntu/logs
    ignore_errors: true
    run_once: true

  - name: 020-setup-client.sh
    sudo: yes
    sudo_user: ubuntu
    shell: |
      cd treasuremap && \
      sudo  ./tools/deployment/airskiff/developer/020-setup-client.sh 2>&1 | tee -a /home/ubuntu/logs
    ignore_errors: yes
    run_once: true

  - name: change ownership of airskiff.yaml
    sudo: yes
    sudo_user: ubuntu
    shell: |
      if [ ! -f "$HOME/treasuremap/airskiff.yaml" ]; then
        touch "$HOME/treasuremap/airskiff.yaml"
      fi
      sudo chmod 0644 "$HOME/treasuremap/airskiff.yaml"
      sudo chown -R ubuntu:ubuntu "$HOME/"
    ignore_errors: true

  - name: Make sure that UCP label is set on all nodes
    sudo: yes
    sudo_user: ubuntu
    shell: |
      kubectl label nodes --all --overwrite ucp-control-plane=enabled
    ignore_errors: true

  - name: 030-armada-bootstrap.sh
    sudo: yes
    sudo_user: ubuntu
    shell: |
      cd treasuremap && \
      sudo ./tools/deployment/airskiff/developer/030-armada-bootstrap.sh 2>&1 | tee -a /home/ubuntu/logs
    ignore_errors: false
    run_once: true

  - name: Setup openrc
    sudo: yes
    sudo_user: ubuntu
    shell: |
      export OS_PASSWORD=$(grep 'password' "$HOME/treasuremap/site/airskiff/secrets/passphrases/osh_keystone_admin_password.yaml" | grep data | awk '{print $2}')
      bash "$HOME/scripts/set-openrc.sh"
    ignore_errors: yes
    run_once: true
