all:
  children:
    primary:
      hosts:
{% for ip in groups['k8s_contr'] %}
        node_contr:
          ansible_port: 22
          ansible_host: {{ ip }}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /etc/openstack-helm/deploy-key.pem
          ansible_ssh_extra_args: -o StrictHostKeyChecking=no
{% endfor %}
    nodes:
      hosts:
{% for ip in groups['k8s_minion'] %}
        node_{{ ip | replace('.', '_') }}:
          ansible_port: 22
          ansible_host: {{ ip }}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /etc/openstack-helm/deploy-key.pem
          ansible_ssh_extra_args: -o StrictHostKeyChecking=no
{% endfor %}
