---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: full-site
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: full-site-global
    actions:
      - method: replace
        path: .chart_groups
      - method: replace
        path: .release_prefix
  storagePolicy: cleartext
data:
  release_prefix: airship
  chart_groups:
    - mynamespace-ingress-controller-airskiff
    - mynamespace-mariadb-airskiff
    - mynamespace-rabbitmq-airskiff
    - mynamespace-memcached-airskiff
    - mynamespace-keystone-airskiff
    - mynamespace-glance-airskiff
    # Enable cinder when Ceph is deployed
    #    - mynamespace-cinder-airskiff
    - mynamespace-compute-kit-airskiff
...
