---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ingress
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-ingress-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        ingress: 3
        error_page: 3
...
