---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-rabbitmq
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-rabbitmq-global
    actions:
      - method: replace
        path: .test
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  timeout: 1800
  test:
    enabled: false
  values:
    pod:
      replicas:
        server: 1
spec:
  template:
    spec:
      containers:
      - name: rabbitmq
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 60
...
