---
- block:
  - name: Set permissions to .ssh dir on contr
    shell: sudo chown -R ubuntu:ubuntu -R .ssh
    delegate_to: "{{ item }}"
    delegate_facts: True
    loop: "{{ groups['k8s_contr'] }}"

  - name: Set permissions to .ssh dir on minions
    shell: chown -R ubuntu:ubuntu -R .ssh
    delegate_to: "{{ item }}"
    delegate_facts: True
    loop: "{{ groups['k8s_minion'] }}"
    run_once: True

  - name: Accept SSH key self k8s_contr
    shell: cat .ssh/id_rsa.pub | tee -a .ssh/authorized_keys
    delegate_to: "{{ item }}"
    delegate_facts: True
    loop: "{{ groups['k8s_contr'] }}"
    run_once: True

  - name: Ensure SSH connectivity between k8s_contr and k8s_minion
    shell: |
        for ip in "{{groups['k8s_minion'] | join(' ') }}"; do
          ssh -oBatchMode=yes -i .ssh/id_rsa -oStrictHostKeyChecking=no "ubuntu@${ip}" uptime;
        done
    retries: 5
    delay: 10
    delegate_to: "{{ item }}"
    delegate_facts: True
    loop: "{{ groups['k8s_contr'] }}"
    register: command_result
    failed_when: "command_result.rc == 1"
    run_once: True
