---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: mynamespace-memcached-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openstack-memcached-global
      component: memcached
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  namespace: mynamespace
  release: mynamespace-memcached
  chart_name: mynamespace-memcached
  wait:
    timeout: 300
    labels:
      release_group: airship-mynamespace-memcached
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-mynamespace-memcached
...
