---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: msite1-memcached-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openstack-memcached-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  release: msite1-memcached
  namespace: msite1
  wait:
    timeout: 9000
    labels:
      release_group: airship-msite1-memcached
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-msite1-memcached
...
