---
- when: setup_minikube
  name: 010-deploy-k8s.sh
  sudo: yes
  sudo_user: ubuntu
  shell: |
    cd treasuremap && \
    ./tools/deployment/airskiff/developer/010-deploy-k8s.sh 2>&1 | tee -a "logs/cluster-logs-{{ ansible_nodename }}-{{ namespace }}"
  ignore_errors: true
  run_once: true
