---
- name: Prepare hosts
  hosts:
    - k8s_contr
    - k8s_minion
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: ".ssh/id_rsa_ansible"
    repo_name: docker.io
  tasks:
    # If you overwrite yaml files and there are images, you need to pull
    # images on all hosts
    - name: "Copy helm charts overwrite yamls"
      copy:
        src: ../../../../helm/
        dest: helm/
        mode: 0644
        group: ubuntu
        owner: ubuntu

    # Someone can have private images
    - name: Pull images from repository
      shell: |
        IMAGES=$(grep "{{ repo_name }}" -r helm/  | awk '{print $2}' | sort | uniq)
        for image in $IMAGES; do
          docker pull $image;
        done
      ignore_errors: true
