---
- when: not setup_airskiff and setup_osh
  block:
  - name: "Copy helm charts overwrite yamls"
    synchronize:
      src: helm/
      dest: helm/

  - name: Pull images from repository
    sudo: yes
    sudo_user: ubuntu
    shell: |
      IMAGES=$(grep "{{ repo_name }}" -r "$HOME/helm/"  | awk '{print $2}' | sed 's/://g' | sort | uniq)
      IMAGE_TAG="master"
      for image in $IMAGES; do
        docker pull "$image:$IMAGE_TAG";
      done
    ignore_errors: true
