---
- name: Defined servers
  hosts: localhost
  vars:
    k8s_hosts:
      k8s_contr:
        - "{{ lookup('env', 'CONTR_NAME') if lookup('env', 'CONTR_NAME') != '' else 'k8s_contr_1' }}"
      k8s_minion:
        - "{{ lookup('env', 'MINION_1') if lookup('env', 'MINION_1') != '' else 'k8s_minion_1'  }}"
#        - "{{ lookup('env', 'MINION_2') if lookup('env', 'MINION_2') != '' else 'k8s_minion_2'  }}"
    contr_flavor: b2-30
    contr_image: "Ubuntu 16.04"
    contr_key_name: ansible_key
    contr_net_name: Ext-Net
    minion_flavor: b2-30
    minion_image: "Ubuntu 16.04"
    minion_key_name: ansible_key
    minion_net_name: Ext-Net
  tasks:
    - name: Info about defined hosts
      debug:
        var: k8s_hosts

    - name: Set k8s_hosts as fact
      set_fact:
        k8s_hosts: "{{ k8s_hosts }}"
        contr_flavor: "{{ contr_flavor }}"
        contr_image: "{{ contr_image }}"
        contr_key_name: "{{ contr_key_name }}"
        contr_net_name: "{{ contr_net_name }}"
        minion_flavor: "{{ minion_flavor }}"
        minion_image: "{{ minion_image }}"
        minion_key_name: "{{ minion_key_name }}"
        minion_net_name: "{{ minion_net_name }}"
