---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: cinder-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: cinder-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  release: mynewnamespace-cinder
  namespace: mynewnamespace
  wait:
    timeout: 300
    labels:
      release_group: airship-mynewnamespace-cinder
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-mynewnamespace-cinder
...
