---
- name: Prepare hosts
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa_ansible
  tasks:
    - name: Clone OSH repo
      sudo: yes
      sudo_user: ubuntu
      shell: /bin/bash -x /home/ubuntu/clone-osh-repo.sh >> /home/ubuntu/logs
      register: clone_status
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"
      ignore_errors: yes
      run_once: True

    - name: Show current groups
      debug:
        var: groups

    - name: Run scripts on k8s_contr
      become: true
      become_user: ubuntu
      shell: /home/ubuntu/setup-controller.sh >> /home/ubuntu/logs
      args:
        executable: /bin/bash
      environment:
        ANSIBLE_LOG_PATH: /home/ubuntu/ansible.logs
        NODE_TWO_IP: "{{ groups['k8s_minion'][0] }}"
        NODE_THREE_IP: "{{ groups['k8s_minion'][1] }}"
      ignore_errors: yes
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"
      register: k8s_deploy
      failed_when: k8s_deploy.rc == 1
      run_once: True
