---
- name: Prepare hosts
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa_ansible
  tasks:
      # temporary workaround
    - name: Check if openrc file exist
      stat:
        path: /home/ubuntu/openrc
      register: openrc_file

    - when: openrc_file.stat.exists == True
      name: Run mariaDB rabbitMQ memcached on k8s_contr
      become: true
      become_user: ubuntu
      shell: |
        if [ -f '/home/ubuntu/helm/helm-args' ]; then
          source /home/ubuntu/helm/helm-args
        fi
        cd /opt/openstack-helm
        nohup timeout 300 ./tools/deployment/multinode/050-mariadb.sh &
        nohup timeout 300 ./tools/deployment/multinode/060-rabbitmq.sh &
        nohup timeout 300 ./tools/deployment/multinode/070-memcached.sh &
        wait
      environment:
        OSH_EXTRA_HELM_ARGS: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS') }}"
        OSH_EXTRA_HELM_ARGS_MARIADB: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_MARIADB') }}"
        OSH_EXTRA_HELM_ARGS_RABBITMQ: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_RABBITMQ') }}"
        OSH_EXTRA_HELM_ARGS_MEMCACHED: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_MEMCACHED') }}"
      delegate_to: "{{ groups['k8s_contr'][0] }}"
      ignore_errors: yes
      register: basic_services_result
      run_once: True

    ###########################################################################

    - name: Run Keystone, RadosGW, openvswitch - test nova and neutron
      become: true
      become_user: ubuntu
      shell: |
        if [ -f '/home/ubuntu/helm/helm-args' ]; then
          source /home/ubuntu/helm/helm-args
        fi

        cd /opt/openstack-helm
        export GLANCE_BACKEND=rbd
        nohup timeout 300 ./tools/deployment/multinode/080-keystone.sh &
        nohup timeout 300 ./tools/deployment/multinode/090-ceph-radosgateway.sh &
        nohup timeout 300 ./tools/deployment/multinode/120-openvswitch.sh  &
        nohup timeout 800 ./tools/deployment/multinode/140-compute-kit.sh &
        wait
      environment:
        OSH_EXTRA_HELM_ARGS: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS') }}"
        OSH_EXTRA_HELM_ARGS_KEYSTONE: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_KEYSTONE') }}"
        OSH_EXTRA_HELM_ARGS_HEAT: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_HEAT') }}"
        OSH_EXTRA_HELM_ARGS_GLANCE: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_GLANCE') }}"
        OSH_EXTRA_HELM_ARGS_CINDER: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_CINDER') }}"
      delegate_to: "{{ groups['k8s_contr'][0] }}"
      ignore_errors: yes
      register: os_services_result
      run_once: True

    - name: Run glance, cinder, heat, barbican and libvirt
      become: true
      become_user: ubuntu
      shell: |
        if [ -f '/home/ubuntu/helm/helm-args' ]; then
          source /home/ubuntu/helm/helm-args
        fi
        cd /opt/openstack-helm
        nohup timeout 300 ./tools/deployment/multinode/100-glance.sh &
        nohup timeout 300 ./tools/deployment/multinode/110-cinder.sh &
        nohup timeout 300 ./tools/deployment/multinode/150-heat.sh &
        nohup timeout 300 ./tools/deployment/multinode/160-barbican.sh &
        nohup timeout 300 ./tools/deployment/multinode/130-libvirt.sh &
        wait
      environment:
        OSH_EXTRA_HELM_ARGS: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS') }}"
        OSH_EXTRA_HELM_ARGS_HEAT: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_HEAT') }}"
        OSH_EXTRA_HELM_ARGS_BARBICAN: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_BARBICAN') }}"
      delegate_to: "{{ groups['k8s_contr'][0] }}"
      ignore_errors: yes
      register: os_services_result
      run_once: True
