---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-ingress-controller
  replacement: true
  labels:
    name: openstack-ingress-controller-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: openstack-ingress-controller-global
      component: ingress
    actions:
      - method: replace
        path: .values.pod
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  chart_name: {{ namespace }}-ingress-controller
  release: {{ namespace }}-ingress-controller
  namespace: {{ namespace }}
  wait:
    timeout: 900
    labels:
      release_group: airship-{{ namespace }}-ingress-controller
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-{{ namespace }}-ingress-controller
  values:
    pod:
      replicas:
        ingress: 3
        error_page: 1
...
