---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: full-site
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: full-site-global
    actions:
      - method: replace
        path: .chart_groups
      - method: replace
        path: .release_prefix
  storagePolicy: cleartext
data:
  release_prefix: airship
  chart_groups:
    - msite1-ingress-controller-airskiff
    - msite1-mariadb-airskiff
    - msite1-rabbitmq-airskiff
    - msite1-memcached-airskiff
    - msite1-keystone-airskiff
    - msite1-glance-airskiff
      #    - msite1-cinder-airskiff
    - msite1-compute-kit-airskiff
...
