---
- name: Install 010-armada-host-setup.sh
  sudo: yes
  sudo_user: ubuntu
  shell: |
    cd /opt/openstack-helm-infra
    bash -x ./tools/deployment/armada/010-armada-host-setup.sh 2>&1 | tee -a logs
  ignore_errors: false
  delegate_to: "{{ groups['airship_contr'][0] }}"
  run_once: True

  # workaround for new pip
- name: Install PyYAML
  sudo: yes
  sudo_user: ubuntu
  shell: |
    sudo -H pip3 install --ignore-installed PyYAML 2>&1 | tee -a logs
  ignore_errors: false
  delegate_to: "{{ groups['airship_contr'] }}"
  run_once: True

- name: Install 015-armada-build.sh
  sudo: yes
  sudo_user: ubuntu
  shell: |
    cd /opt/openstack-helm-infra
    bash -x ./tools/deployment/armada/015-armada-build.sh 2>&1 | tee -a logs
  ignore_errors: false
  delegate_to: "{{ groups['airship_contr'] }}"
  run_once: True

- name: Install 020-armada-render-manifests.sh
  sudo: yes
  sudo_user: ubuntu
  shell: |
    cd /opt/openstack-helm-infra
    bash -x ./tools/deployment/armada/020-armada-render-manifests.sh 2>&1 | tee -a logs
  ignore_errors: false
  delegate_to: "{{ groups['airship_contr'] }}"
  run_once: True

- name: Install 025-armada-validate-manifests.sh
  sudo: yes
  sudo_user: ubuntu
  shell: |
    cd /opt/openstack-helm-infra
    bash -x ./tools/deployment/armada/025-armada-validate-manifests.sh 2>&1 | tee -a logs
  ignore_errors: false
  delegate_to: "{{ groups['airship_contr'] }}"
  run_once: True

- name: Install 030-armada-apply-manifests.sh
  sudo: yes
  sudo_user: ubuntu
  shell: |
    cd /opt/openstack-helm-infra
    bash -x ./tools/deployment/armada/030-armada-apply-manifests.sh 2>&1 | tee -a logs
  ignore_errors: false
  delegate_to: "{{ groups['airship_contr'] }}"
  run_once: True

- name: Install 035-armada-update-uuids.sh
  sudo: yes
  sudo_user: ubuntu
  shell: |
    cd /opt/openstack-helm-infra
    bash -x ./tools/deployment/armada/035-armada-update-uuids.sh 2>&1 | tee -a logs
  ignore_errors: false
  delegate_to: "{{ groups['airship_contr'] }}"
  run_once: True

- name: Install 040-armada-update-passwords.sh
  sudo: yes
  sudo_user: ubuntu
  shell: |
    cd /opt/openstack-helm-infra
    bash -x ./tools/deployment/armada/040-armada-update-passwords.sh 2>&1 | tee -a logs
  ignore_errors: false
  delegate_to: "{{ groups['airship_contr'] }}"
  run_once: True
