---
- name: Install required services
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: "/home/ubuntu/.ssh/id_rsa_ansible"
  tasks:
    - name: Check if openrc file exist
      stat:
        path: /home/ubuntu/openrc
      register: openrc_file

    - when: openrc_file.stat.exists == True
      name: Run setup-client and ingress on k8s_contr
      become: true
      become_user: ubuntu
      shell: |
          set timeout 300
          cd /opt/openstack-helm
          nohup ./tools/deployment/multinode/010-setup-client.sh &
          nohup ./tools/deployment/multinode/020-ingress.sh &
          wait
      environment:
        OSH_EXTRA_HELM_ARGS: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS') }}"
        OSH_EXTRA_HELM_ARGS_INGRESS_KUBE_SYSTEM: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_INGRESS_KUBE_SYSTEM') }}"
      delegate_to: "{{ groups['k8s_contr'][0] }}"
      ignore_errors: yes
      register: client_setup
      run_once: True

    - when: (client_setup | success)
      name: Run Ceph on k8s_contr
      become: true
      become_user: ubuntu
      shell: |
          set timeout 500
          cd /opt/openstack-helm
          nohup ./tools/deployment/multinode/030-ceph.sh &
          wait
      environment:
        OSH_EXTRA_HELM_ARGS: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS') }}"
        OSH_EXTRA_HELM_ARGS_CEPH_DEPLOY: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_CEPH_DEPLOY') }}"
      delegate_to: "{{ groups['k8s_contr'][0] }}"
      ignore_errors: yes
      register: ceph_result
      run_once: True

    - when: (ceph_result | success)
      name: Run Ceph-NS-Activate on k8s_contr
      become: true
      become_user: ubuntu
      shell: |
          set timeout 500
          cd /opt/openstack-helm
          nohup ./tools/deployment/multinode/040-ceph-ns-activate.sh &
          wait
      environment:
        OSH_EXTRA_HELM_ARGS: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS') }}"
        OSH_EXTRA_HELM_ARGS_CEPH_NS_ACTIVATE: "{{ lookup('env', 'OSH_EXTRA_HELM_ARGS_CEPH_NS_ACTIVATE') }}"
      delegate_to: "{{ groups['k8s_contr'][0] }}"
      ignore_errors: yes
      register: ceph_ns_activate_result
      run_once: True

