---
- block:
  - name: Generate temporary ssh key that will be used by contr
    openssh_keypair:
      path: "/tmp/{{ ssh_name }}"
    vars:
      - ssh_name: "ssh-{{ 99999999 | random }}"
    register: ssh_keygen_result

  - name: Install private key on k8s_contr
    copy:
      src: "{{ ssh_keygen_result.filename }}"
      dest: .ssh/id_rsa
      mode: 0600
      group: ubuntu
      owner: ubuntu
    delegate_to: "{{ item }}"
    delegate_facts: True
    loop: "{{ groups['k8s_contr'] }}"
    ignore_errors: false

  - name: Install public key on all hosts
    copy:
      src: "{{ ssh_keygen_result.filename }}.pub"
      dest: .ssh/id_rsa.pub
      mode: 0600
      group: ubuntu
      owner: ubuntu
    delegate_to: "{{ item }}"
    delegate_facts: True
    loop: "{{ groups['all'] }}"
    ignore_errors: false

  - when: "{{ additional_ssh_key != '' }}"
    copy:
      src: "{{ additional_ssh_key }}"
      dest: .ssh/additional_ssh_key.pub
      mode: 0600
      group: ubuntu
      owner: ubuntu
    delegate_to: "{{ item }}"
    delegate_facts: True
    loop: "{{ groups['all'] }}"
    ignore_errors: false

