---
- name: Change sudoers
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: "/home/ubuntu/.ssh/id_rsa_ansible"
  tasks:
    - name: Change sudoers file
      sudo: yes
      sudo_user: ubuntu
      shell: sudo bash /home/ubuntu/scripts/change-sudoers.sh
      ignore_errors: false
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"
