---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: {{ namespace }}-neutron
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: neutron-global
      component: neutron
    actions:
      - method: merge
        path: .
      - method: replace
        path: .values.labels.agent.l3
      - method: replace
        path: .values.network
      - method: replace
        path: .values.conf.neutron
      - method: replace
        path: .values.conf.plugins
      - method: replace
        path: .values.conf.auto_bridge_add.br-ex
  storagePolicy: cleartext
data:
  chart_name: {{ namespace }}-neutron
  release: {{ namespace }}-neutron
  namespace: {{ namespace }}
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-{{ namespace }}-neutron
  wait:
    timeout: 1200
    labels:
      release_group: airship-{{ namespace }}-neutron
  values:
    pod:
      replicas:
        server: 3
    labels:
      agent:
        l3:
          node_selector_key: openstack-control-plane
          node_selector_value: enabled
    network:
      interface:
        tunnel: docker0
    conf:
      neutron:
        DEFAULT:
          l3_ha: False
          max_l3_agents_per_router: 1
          l3_ha_network_type: vxlan
          dhcp_agents_per_network: 1
      plugins:
        ml2_conf:
          ml2_type_flat:
            flat_networks: public
        openvswitch_agent:
          agent:
            tunnel_types: vxlan
          ovs:
            bridge_mappings: public:br-ex
        linuxbridge_agent:
          linux_bridge:
            bridge_mappings: public:br-ex
      auto_bridge_add:
        br-ex: docker0
# it is not required for Ocata - for now default OSH image relase
# https://github.com/openstack/openstack-helm/blob/master/neutron/values_overrides/stein.yaml
{% if treasuremap_params['OPENSTACK_RELEASE'] is defined %}
      paste:
        app:neutronversions:
          paste.app_factory: neutron.pecan_wsgi.app:versions_factory
    pod:
      probes:
        dhcp_agent:
          dhcp_agent:
            readiness:
              enabled: false
            liveness:
              enabled: false
        l3_agent:
          l3_agent:
            readiness:
              enabled: false
            liveness:
              enabled: false
        metadata_agent:
          metadata_agent:
            readiness:
              enabled: false
            liveness:
              enabled: false
        ovs_agent:
          ovs_agent:
            liveness:
              enabled: false
        sriov_agent:
          sriov_agent:
            readiness:
              enabled: false
{% endif %}

{% if treasuremap_params['NEUTRON_IMAGE'] is defined %}
    images:
      tags:
        neutron_db_sync: {{ treasuremap_params['NEUTRON_IMAGE'] }}
        neutron_server: {{ treasuremap_params['NEUTRON_IMAGE'] }}
        neutron_dhcp: {{ treasuremap_params['NEUTRON_IMAGE'] }}
        neutron_metadata: {{ treasuremap_params['NEUTRON_IMAGE'] }}
        neutron_l3: {{ treasuremap_params['NEUTRON_IMAGE'] }}
        neutron_l2gw: {{ treasuremap_params['NEUTRON_IMAGE'] }}
        neutron_openvswitch_agent: {{ treasuremap_params['NEUTRON_IMAGE'] }}
        neutron_linuxbridge_agent: {{ treasuremap_params['NEUTRON_IMAGE'] }}
        neutron_bagpipe_bgp: {{ treasuremap_params['NEUTRON_IMAGE'] }}
{% if treasuremap_params['HEAT_IMAGE'] is defined %}
        bootstrap: {{ treasuremap_params['HEAT_IMAGE'] }}
        db_init: {{ treasuremap_params['HEAT_IMAGE'] }}
        db_drop: {{ treasuremap_params['HEAT_IMAGE'] }}
        ks_user: {{ treasuremap_params['HEAT_IMAGE'] }}
        ks_service: {{ treasuremap_params['HEAT_IMAGE'] }}
        ks_endpoints: {{ treasuremap_params['HEAT_IMAGE'] }}
{% endif %}
{% endif %}
...
