---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-mariadb-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openstack-mariadb-global
      component: mariadb
    actions:
      - method: delete
        path: .values.labels.prometheus_mysql_exporter
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        server: 1
  release: mynewnamespace-mariadb
  namespace: mynewnamespace
  wait:
    timeout: 600
    labels:
      release_group: airship-mynewnamespace-mariadb
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-mynewnamespace-mariadb
...
