---
- when: setup_airskiff and treasuremap_overwrite
  block:
  - name: Check if trasuremap exists
    stat:
      path: treasuremap
    register: treasuremap_dir

  - when: treasuremap_dir.stat.exists
    name: Copy airskiff site to other namespace eg msite1
    shell: |
      cp -av treasuremap/site/airskiff "treasuremap/site/{{ namespace }}"
    ignore_errors: true

  - when: treasuremap_dir.stat.exists
    name: Copy trasuremap overwrite files
    synchronize:
      src: airship-overwrite/mynamespace/
      dest: "treasuremap/site/{{ namespace }}"

  - name: Copy trasuremap overwrite files
    synchronize:
      src: airship-overwrite/tools/
      dest: treasuremap/tools/

  - name: Change namespace to defined one
    shell: |
      find treasuremap -type f -exec sed -i -e "s/mynamespace/{{ namespace }}/g" {} \;
    ignore_errors: true

  # FIXME: install openvswitch not in the container, but on the host.
  # It is not posssible to run openvswitch in multiple namespaces (without
  # a lot of changes)
