---
- when: treasuremap_overwrite
  name: Check if trasuremap exists
  stat:
    path: treasuremap
  register: treasuremap_dir

- when: treasuremap_dir.stat.exists and treasuremap_dir.stat.isdir and treasuremap_overwrite
  name: Copy airskiff site to other namespace eg msite1
  shell: |
    cp -av treasuremap/site/airskiff "treasuremap/site/{{ namespace }}"
#    mkdir -p treasuremap/site/msite1/software/
#    cp -av treasuremap/site/airskiff/software/charts/kubernetes "treasuremap/site/{{ namespace }}/software/charts/kubernetes"
#    cp -av treasuremap/site/airskiff/software/charts/osh-infra "treasuremap/site/{{ namespace}} /software/charts/osh-infra"
#    cp -av treasuremap/site/airskiff/software/charts/ucp "treasuremap/site/{{ namespace }}/software/charts/ucp"
  ignore_errors: true

- when: treasuremap_dir.stat.exists and treasuremap_dir.stat.isdir and treasuremap_overwrite
  name: Copy trasuremap overwrite files
  synchronize:
    src: airship-overwrite/mynamespace/
    dest: "treasuremap/site/{{ namespace }}"

- when: treasuremap_overwrite
  name: Change namespace to defined one
  shell: |
    find treasuremap -type f -exec sed -i -e "s/mynamespace/{{ namespace }}/g" {} \;
  ignore_errors: true

# FIXME: install openvswitch not in the container, but on the host.
# It is not posssible to run openvswitch in multiple namespaces (without
# a lot of changes)
