---
- when: treasuremap_overwrite
  name: Check if trasuremap exists
  stat:
    path: treasuremap
  register: treasuremap_dir

- when: treasuremap_dir.stat.exists and treasuremap_overwrite
  name: Copy trasuremap overwrite files
  synchronize:
    src: airship-overwrite/
    dest: treasuremap/

- when: treasuremap_dir.stat.exists and treasuremap_overwrite
  name: Copy required files to site dir because symlinks are not supported
  shell: |
    cp -av treasuremap/site/airskiff/software/charts/kubernetes treasuremap/site/msite1/software/charts/kubernetes
    cp -av treasuremap/site/airskiff/software/charts/osh-infra treasuremap/site/msite1/software/charts/osh-infra
    cp -av treasuremap/site/airskiff/software/charts/ucp treasuremap/site/msite1/software/charts/ucp
  ignore_errors: true
