---
- name: Copy required scripts
  hosts: localhost
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: Copy controller script
      copy:
        src: "{{ playbook_dir }}/../files/scripts/"
        dest: scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
        follow: yes
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"

    - name: Copy upgrade host script to minion
      copy:
        src: "{{ playbook_dir }}/../files/scripts/upgrade-host.sh"
        dest: scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
        follow: yes
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_minion'] }}"

    - name: Copy setup new host script to minion
      copy:
        src: "{{ playbook_dir }}/../files/scripts/setup-new-host.sh"
        dest: scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
        follow: yes
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_minion'] }}"

    - name: Copy setup new host script to minion
      copy:
        src: "{{ playbook_dir }}/../files/scripts/install-kubernetes.sh"
        dest: scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
        follow: yes
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_minion'] }}"
