---
- name: Copy required scripts
  hosts:
    - k8s_contr
    - k8s_minion
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: "/home/ubuntu/.ssh/id_rsa_ansible"
  tasks:
    - name: Copy controller script
      copy:
        src: /home/ubuntu/openstack-helm-deployment/scripts/
        dest: /home/ubuntu/scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"

    - name: Copy upgrade host script to minion
      copy:
        src: /home/ubuntu/openstack-helm-deployment/scripts/upgrade-host.sh
        dest: /home/ubuntu/scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_minion'] }}"

    - name: Copy setup new host script to minion
      copy:
        src: /home/ubuntu/openstack-helm-deployment/scripts/setup-new-host.sh
        dest: /home/ubuntu/scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_minion'] }}"

    - name: Copy setup new host script to minion
      copy:
        src: /home/ubuntu/openstack-helm-deployment/scripts/install-kubernetes.sh
        dest: /home/ubuntu/scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_minion'] }}"
