---
- name: Copy required scripts
  hosts: localhost
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: ".ssh/id_rsa_ansible"
  tasks:
    - name: Copy controller script
      copy:
        src: "{{ repo_dir }}/scripts/"
        dest: scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"

    - name: Copy upgrade host script to minion
      copy:
        src: "{{ repo_dir }}/scripts/upgrade-host.sh"
        dest: scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_minion'] }}"

    - name: Copy setup new host script to minion
      copy:
        src: "{{ repo_dir }}/scripts/setup-new-host.sh"
        dest: scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_minion'] }}"

    - name: Copy setup new host script to minion
      copy:
        src: "{{ repo_dir }}/scripts/install-kubernetes.sh"
        dest: scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_minion'] }}"
