---
- name: Prepare hosts
  hosts:
    - k8s_minion
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: Run scripts on k8s_minion
      sudo: yes
      sudo_user: ubuntu
      command: /bin/bash -x /home/ubuntu/setup-new-host.sh > /home/ubuntu/logs
      register: current_status
      failed_when: current_status.rc == 1
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_minion'] }}"
