---
- name: Prepare hosts
  hosts:
    - airship_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa_ansible
  tasks:
    - name: Check if openrc file exist
      stat:
        path: /home/ubuntu/openrc
      register: openrc_file

    - when: openrc_file.stat.exists == True
      name: Copy tempest conf
      copy:
        src: /home/ubuntu/openstack-helm-deployment/multinode/tempest/tempest.conf
        dest: /home/ubuntu/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['airship_contr'] }}"

    - name: Copy tempest conf
      copy:
        src: /home/ubuntu/openstack-helm-deployment/multinode/tempest/run-tempest.sh
        dest: /home/ubuntu/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ groups['airship_contr'][0] }}"

    - name: Copy whitelist
      copy:
        src: /home/ubuntu/openstack-helm-deployment/multinode/tempest/whitelist.list
        dest: /home/ubuntu/
        mode: 0644
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ groups['airship_contr'][0] }}"

    - name: Copy blacklist
      copy:
        src: /home/ubuntu/openstack-helm-deployment/multinode/tempest/blacklist.list
        dest: /home/ubuntu/
        mode: 0644
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ groups['airship_contr'][0] }}"

    - name: Copy prepare-tempest.sh script
      copy:
        src: /home/ubuntu/openstack-helm-deployment/multinode/tempest/prepare-tempest.sh
        dest: /home/ubuntu/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ groups['airship_contr'][0] }}"

    - name: Execute tempest test
      shell: bash -x /home/ubuntu/prepare-tempest.sh
      register: tempest_output

    - name: Execute tempest test
      shell: bash -x /home/ubuntu/run-tempest.sh
      register: tempest_output
      environment:
        WHITELIST_FILE: /home/ubuntu/whitelist.list
        BLACKLIST_FILE: /home/ubuntu/blacklist.list
