---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: full-site
  labels:
    name: full-site-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: full-site-global
    actions:
      - method: replace
        path: .chart_groups
  storagePolicy: cleartext
data:
  chart_groups:
    - openstack-ingress-controller
    - openstack-mariadb
    - openstack-rabbitmq
    - openstack-memcached
    - openstack-keystone
    - openstack-glance
    - openstack-compute-kit
    #- openstack-heat
    # NOTE: leave it as template. In the future, ceph will be added.
...
