---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: keystone
  replacement: true
  labels:
    name: keystone-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: keystone-global
      component: keystone
    actions:
      - method: replace
        path: .values.pod
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  chart_name: {{ namespace }}-keystone
  release: {{ namespace }}-keystone
  namespace: {{ namespace }}
  wait:
    timeout: 600
    labels:
      release_group: airship-{{ namespace }}-keystone
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-{{ namespace }}-keystone
  values:
    pod:
      replicas:
        api: 3
...
