---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  labels:
    name: mynewnamespace-ingress-controller-global
  name: openstack-ingress-controller-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openstack-ingress-controller-global
      component: ingress
    actions:
      - method: replace
        path: .values.pod
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        ingress: 1
        error_page: 1
  release: mynewnamespace-ingress-controller
  namespace: mynewnamespace
  wait:
    timeout: 600
    labels:
      release_group: airship-mynewnamespace-ingress-controller
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-mynewnamespace-ingress-controller
...
