---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: msite1-mariadb-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openstack-mariadb-global
      component: mariadb
    actions:
      - method: merge
        path: .
      - method: merge
        path: .values.pod
      - method: delete
        path: .values.labels.prometheus_mysql_exporter
  storagePolicy: cleartext
data:
  chart_name: msite1-mariadb
  release: msite1-mariadb
  namespace: msite1
  wait:
    timeout: 300
    labels:
      release_group: airship-msite1-mariadb
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-msite1-mariadb
  values:
    pod:
      replicas:
        server: 1
...
