---

- name: Create servers
  hosts: localhost
  gather_facts: False
  vars:
    flavor: b2-30
    image: "Ubuntu 16.04"
    key_name: ansible_key
    net_name: Ext-Net
  tasks:
    - name: Set OS configuration as fact
      set_fact:
        flavor: "{{ flavor }}"
        image: "{{ image }}"
        key_name: "{{ key_name }}"
        net_name: "{{ net_name }}"

    - name: "Spawning airship_in_the_bottle node"
      os_server:
        state: present
        auth:
          auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
          username: "{{ lookup('env', 'OS_USERNAME') }}"
          password: "{{ lookup('env', 'OS_PASSWORD') }}"
          project_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
          user_domain_name: "{{ lookup('env', 'OS_USER_DOMAIN_NAME') }}"
          project_domain_name: "{{ lookup('env', 'OS_PROJECT_DOMAIN_NAME') }}"
        region_name: "{{ lookup('env', 'OS_REGION_NAME') }}"
        image: "{{ image }}"
        key_name: "{{ key_name }}"
        timeout: 200
        flavor: "{{ flavor }}"
        nics:
          - net-name: "{{ net_name }}"
        name: "{{ item }}"
      register: airship_in_the_bottle_result
      with_items:
        - "airship-in-the-bottle"

    - name: test
      debug:
        var: airship_in_the_bottle_result

    - name: Add airship_in_the_bottle into local inventory
      add_host:
        name: "{{ airship_in_the_bottle_result.results[0].openstack.public_v4  }}"
        hostname: "{{ airship_in_the_bottle_result.results[0].openstack.name }}"
        group: airship_in_the_bottle

    - name: wait for instances k8s_contr to be ready
      wait_for:
        port: 22
        delay: 5
        timeout: 150
        host: "{{ item }}"
      with_items: "{{ groups['airship_in_the_bottle'] }}"
      run_once: true

    - name: Add airship_in_the_bottle host key to known_hosts
      shell: ssh-keyscan -H "{{ item }}" >> /home/ubuntu/.ssh/known_hosts
      with_items: "{{ groups['airship_in_the_bottle'] }}"
      args:
        executable: /bin/bash
      run_once: True


- name: Deploy
  hosts:
    - airship_in_the_bottle
  gather_facts: False
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa_ansible
  tags:
    - deplot
  tasks:
    - name: "Copy upgrade script"
      copy:
        src: /home/ubuntu/openstack-helm-deployment/scripts/upgrade-host.sh
        dest: /home/ubuntu/
        mode: 0755
        group: ubuntu
        owner: ubuntu

    - name: "Copy airship install script"
      copy:
        src: /home/ubuntu/openstack-helm-deployment/scripts/airship-in-a-bottle.sh
        dest: /home/ubuntu/
        mode: 0755
        group: ubuntu
        owner: ubuntu

    - name: Move script to root dir
      sudo: yes
      sudo_user: ubuntu
      shell: /usr/bin/sudo mv /home/ubuntu/airship-install.sh /root/airship-install.sh
      ignore_errors: true

    - name: remove nano
      sudo: yes
      sudo_user: ubuntu
      shell: /usr/bin/sudo /usr/bin/apt remove -y nano
      ignore_errors: true

    - name: Upgrade host
      sudo: yes
      sudo_user: ubuntu
      shell: /home/ubuntu/upgrade-host.sh | tee -a /home/ubuntu/logs
      register: upgrade_status
      ignore_errors: yes
      run_once: True

    - name: Upgrade host
      sudo: yes
      sudo_user: root
      shell: /bin/bash /root/airship-install.sh >> /home/ubuntu/logs 2>&1
      register: install_status
      ignore_errors: yes
      run_once: True
