---
- name: Add VMs to known hosts
  hosts: localhost
  remote_user: ubuntu
  gather_facts: False
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa_ansible
  tags:
    - ansible_host_ssh_known_hosts
  tasks:
    - name: Add airship_contr host key to known_hosts
      shell: ssh-keyscan -H "{{ item }}" >> /home/ubuntu/.ssh/known_hosts
      with_items: "{{ groups['airship_contr'] }}"
      args:
        executable: /bin/bash
      run_once: True

    - name: Add airship_minion host key to known_hosts
      shell: ssh-keyscan -H "{{ item }}" >> /home/ubuntu/.ssh/known_hosts
      with_items: "{{ groups['airship_minion'] }}"
      args:
        executable: /bin/bash
      run_once: True

- name: Configure known_hosts on contr
  hosts:
    - airship_contr
  remote_user: ubuntu
  gather_facts: False
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa_ansible
  tags:
    - contr_known_hosts
  tasks:
    - name: Accept SSH key between airship_contr and own self
      shell: |
          for ip in "{{ groups['airship_contr'] | join(' ') }}"; do
              ssh-keyscan -H "${ip}" >> /home/ubuntu/.ssh/known_hosts;
          done
      args:
        executable: /bin/bash
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['airship_contr'] }}"
      run_once: True

    - name: Accept SSH key between airship_minion and airship_contr
      shell: |
          for ip in "{{ groups['airship_minion'] | join(' ') }}"; do
            ssh-keyscan -H "${ip}" >> /home/ubuntu/.ssh/known_hosts;
          done
      args:
        executable: /bin/bash
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['airship_contr'] }}"
      run_once: True


- name: Generate ansible ssh key and add known_hosts
  hosts:
    - airship_contr
    - airship_minion
  remote_user: ubuntu
  gather_facts: False
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa_ansible
  tags:
    - ssh_known_hosts
  tasks:
    - name: Set permissions to .ssh dir on contr
      shell: sudo chown -R ubuntu:ubuntu -R /home/ubuntu/.ssh
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['airship_contr'] }}"

    - name: "Install private key on airship_contr"
      copy:
        src: /home/ubuntu/.ssh/id_rsa_ansible
        dest: /home/ubuntu/.ssh/id_rsa
        mode: 0600
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{item}}"
      delegate_facts: True
      loop: "{{ groups['airship_contr'] }}"

    - name: "Install public key on all hosts"
      copy:
        src: /home/ubuntu/.ssh/id_rsa_ansible.pub
        dest: /home/ubuntu/.ssh/id_rsa.pub
        mode: 0600
        group: ubuntu
        owner: ubuntu
      run_once: True

    - name: "Install public key on airship_minion"
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa_ansible.pub') }}"
      run_once: True
      delegate_to: "{{item}}"
      delegate_facts: True
      loop: "{{groups['airship_minion']}}"

    - name: "Install public key on airship_contr"
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa_ansible.pub') }}"
      run_once: True
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['airship_contr'] }}"


    - name: Set permissions to .ssh dir on minions
      shell: chown -R ubuntu:ubuntu -R /home/ubuntu/.ssh
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['airship_minion'] }}"
      run_once: True

    - name: Accept SSH key self airship_contr
      shell: cat /home/ubuntu/.ssh/id_rsa.pub >> /home/ubuntu/.ssh/authorized_keys
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['airship_contr'] }}"
      run_once: True

    - name: "Ensure SSH connectivity between airship_contr and airship_minion"
      shell: |
          for ip in "{{groups['airship_minion'] | join(' ') }}"; do
            ssh -oBatchMode=yes -i /home/ubuntu/.ssh/id_rsa -oStrictHostKeyChecking=no "ubuntu@${ip}" uptime;
          done
      retries: 5
      delay: 10
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['airship_contr'] }}"
      register: command_result
      failed_when: "command_result.rc == 1"
      run_once: True
