---
- name: Check if openrc file exist
  stat:
    path: openrc
  register: openrc_file

- when:  openrc_file.stat.exists == False
  fail:
    msg: "Could not find openrc file. Can't continue"

- name: Copy tempest conf
  synchronize:
    src: tempest/
    dest: tempest/

- name: Check if trasuremap exists
  stat:
    path: treasuremap
  register: treasuremap_dir

- when: treasuremap_dir.stat.exists and treasuremap_dir.stat.isdir
  name: Check if Airship Shipyard has finished its work
  sudo: yes
  sudo_user: ubuntu
  shell: |
    if [ -d 'treasuremap' ]; then
      bash -x scripts/check-shipyard-actions.sh 2>&1 | tee -a tempest-preparation-logs
    fi
  ignore_errors: false
  environment:
    ACTION_NAME: ''
    TIMEOUT: 2000

- when: treasuremap_dir.stat.exists
  name: Wait for services to be deployed on airskiff host
  sudo: yes
  sudo_user: ubuntu
  shell: |
    bash -x openstack-helm-infra/tools/deployment/common/wait-for-pods.sh openstack 2>&1 | tee -a tempest-preparation-logs
  ignore_errors: false

- when: not treasuremap_dir.stat.exists
  name: Wait for services to be deployed on openstack host
  sudo: yes
  sudo_user: ubuntu
  shell: |
    bash -x /opt/openstack-helm-infra/tools/deployment/common/wait-for-pods.sh openstack 2>&1 | tee -a tempest-preparation-logs
  ignore_errors: false

- name: Check services replication
  sudo: yes
  sudo_user: ubuntu
  shell: |
    bash -x scripts/check-service-replication.sh 2>&1 | tee -a tempest-preparation-logs
  environment:
    NAMESPACE: "{{ namespace }}"

- name: Prepare tempest test
  sudo: yes
  sudo_user: ubuntu
  shell: |
    bash -x scripts/prepare-tempest.sh 2>&1 | tee -a tempest-preparation-logs
  register: tempest_output
  environment:
    OPENRC_PATH: "{{ openrc_path }}"

- name: Execute tempest test
  sudo: yes
  sudo_user: ubuntu
  shell: |
    bash -x scripts/run-tempest.sh 2>&1 | tee -a tempest-test-output
  register: tempest_output
  environment:
    WHITELIST_FILE: "{{ whitelist_file }}"
    BLACKLIST_FILE: "{{ blacklist_file }}"
    TEMPEST_PARAMS: "{{ tempest_params }}"
    TEMPEST_BRANCH: "{{ tempest_branch }}"

- when: Get tempest_output var
  debug:
    var: tempest_output
