---
- name: Prepare hosts
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: ".ssh/id_rsa_ansible"
  tasks:
    - name: Check if openrc file exist
      stat:
        path: openrc
      register: openrc_file

    - when: openrc_file.stat.exists == True
      name: Copy tempest conf
      copy:
        src: ../../../tempest/tempest/
        dest: tempest/
        mode: 0755
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"

    - name: Execute tempest test
      shell: bash -x tempest/prepare-tempest.sh
      register: tempest_output

    - name: Execute tempest test
      shell: bash -x tempest/run-tempest.sh
      register: tempest_output
      environment:
        WHITELIST_FILE: tempest/whitelist.list
        BLACKLIST_FILE: tempest/blacklist.list
