---
- name: Check if openrc file exist
  stat:
    path: openrc
  register: openrc_file

- when:  openrc_file.rc == 0
  fail:
    msg: "Could not find openrc file. Can't continue"

- name: Copy tempest conf
  synchronize:
    src: tempest/
    dest: tempest/

- name: Check if Airship Shipyard has finished its work
  sudo: yes
  sudo_user: ubuntu
  shell: |
    if [ -d "treasuremap" ] && [ -d "tempest" ]; then
      bash -x tempest/check-shipyard-actions.sh >> tempest/tempest-logs 2>&1
    else
      exit 1
    fi
  ignore_errors: false
  environment:
    ACTION_NAME: ''
    TIMEOUT: 1500

- name: Wait for services to be deployed
  sudo: yes
  sudo_user: ubuntu
  shell: |
    bash -x openstack-helm-infra/tools/deployment/common/wait-for-pods.sh openstack >> tempest/tempest-logs 2>&1
  ignore_errors: false

- name: Prepare tempest test
  sudo: yes
  sudo_user: ubuntu
  shell: |
    bash -x tempest/prepare-tempest.sh >> tempest/tempest-logs 2>&1
  register: tempest_output

- name: Execute tempest test
  sudo: yes
  sudo_user: ubuntu
  shell: |
    bash -x tempest/run-tempest.sh >> tempest/tempest-test-output 2>&1
  register: tempest_output
  environment:
    WHITELIST_FILE: tempest/whitelist.list
    BLACKLIST_FILE: tempest/blacklist.list
    TEMPEST_PARAMS: "--concurrency 8"
    TEMPEST_BRANCH: "master"

- when: Get tempest_output var
  debug:
    var: tempest_output
