---
- name: Clone OSH repo
  sudo: yes
  sudo_user: ubuntu
  shell: bash -x scripts/clone-osh-repo.sh 2>&1 | tee -a "logs/cluster-logs-{{ ansible_nodename }}-{{ namespace }}"
  register: clone_status
  ignore_errors: yes
  run_once: True

- name: check if OSH infra dir exists
  stat:
    path: /opt/openstack-helm-infra
  register: osh_infra_dir

- when: osh_infra_dir.stat.isdir
  name: Generate OSH infra inventory
  template:
    src: "{{ item }}"
    dest: /opt/openstack-helm-infra/tools/gate/devel/multinode-inventory.yaml
    owner: ubuntu
    group: ubuntu
  with_fileglob:
    - templates/multinode-inventory.yaml

- name: Show current groups
  debug:
    var: groups

# Set k8s version: https://github.com/openstack/openstack-helm-infra/blob/master/tools/deployment/common/005-deploy-k8s.sh#L21
- name: Run scripts on k8s_contr
  become: true
  become_user: ubuntu
  shell: scripts/setup-controller.sh 2>&1 | tee -a "logs/cluster-logs-{{ ansible_nodename }}-{{ namespace }}"
  args:
    executable: /bin/bash
  environment:
    ANSIBLE_LOG_PATH: ansible.logs
    KUBE_VERSION: "{{ kube_version }}"
  run_once: True
  ignore_errors: True
