---
- name: Clone OSH repo
  sudo: yes
  sudo_user: ubuntu
  shell: /bin/bash -x scripts/clone-osh-repo.sh | tee -a logs
  register: clone_status
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['k8s_contr'] }}"
  ignore_errors: yes
  run_once: True

- name: Show current groups
  debug:
    var: groups

# Set k8s version: https://github.com/openstack/openstack-helm-infra/blob/master/tools/deployment/common/005-deploy-k8s.sh#L21
- name: Run scripts on k8s_contr
  become: true
  become_user: ubuntu
  shell: scripts/setup-controller.sh | tee -a logs
  args:
    executable: /bin/bash
  environment:
    ANSIBLE_LOG_PATH: ansible.logs
    NODE_TWO_IP: "{{ groups['k8s_minion'][0] }}"
    NODE_THREE_IP: "{{ groups['k8s_minion'][1] if (groups['k8s_minion'] | length>1) }}"
    KUBE_VERSION: "{{ lookup('env', 'KUBE_VERSION') | default('v1.13.7') }}"
  ignore_errors: yes
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['k8s_contr'] }}"
  register: k8s_deploy
  failed_when: k8s_deploy.rc == 1
  run_once: True
