---
- name: Install newest Docker
  hosts:
    - k8s_contr
    - k8s_minion
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: Check if docker is installed
      command: dpkg-query -l docker-ce
      register: docker_check

    - when: docker_check.stdout.find('no packages found') != -1
      name: Get docker
      shell: curl -sSL https://get.docker.com/ | sh
      run_once: True

    - name: Get docker
      shell: sudo usermod -aG docker ubuntu
      run_once: True
