---
- name: Get log outputs
  sudo: yes
  sudo_user: ubuntu
  synchronize:
    mode: pull
    src: "{{ item }}"
    dest: "{{ lookup('env','HOME') }}/logs/"
    with_lines: "find logs/ -name *-{{ namespace }}"
  run_once: true
  ignore_errors: true
