---
- name: Install newest Docker
  hosts:
    - k8s_contr
    - k8s_minion
  strategy: free
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa_ansible
  tasks:
    - name: Check if docker is installed
      shell: dpkg -l | grep -q 'docker-ce'
      register: docker_check
      ignore_errors: true

    - when: docker_check.rc == 1
      name: Get docker
      shell: curl -sSL https://get.docker.com/ | sh

    - name: Get docker
      shell: sudo usermod -aG docker ubuntu
      ignore_errors: true
