---
- name: Upload custom docker image list
  template:
    src: "{{ item }}"
    dest: "treasuremap/site/{{ namespace }}/software/config/"
    owner: ubuntu
    group: ubuntu
  with_fileglob:
    - templates/site/software/config/*.yaml
