---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-mariadb
  replacement: true
  labels:
    name: openstack-mariadb-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: openstack-mariadb-global
      component: mariadb
    actions:
      - method: merge
        path: .values.pod
      - method: delete
        path: .values.labels.prometheus_mysql_exporter
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  chart_name: {{ namespace }}-mariadb
  release: {{ namespace }}-mariadb
  namespace: {{ namespace }}
  values:
    pod:
      replicas:
        server: 3
  wait:
    timeout: 900
    labels:
      release_group: airship-{{ namespace }}-mariadb
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-{{ namespace }}-mariadb
...
