images:
  tags:
    bootstrap: docker.io/openstackhelm/heat:master-ubuntu_bionic
    db_drop: docker.io/openstackhelm/heat:master-ubuntu_bionic
    db_init: docker.io/openstackhelm/heat:master-ubuntu_bionic
    ks_user: docker.io/openstackhelm/heat:master-ubuntu_bionic
    ks_service: docker.io/openstackhelm/heat:master-ubuntu_bionic
    ks_endpoints: docker.io/openstackhelm/heat:master-ubuntu_bionic
    nova_api: docker.io/openstackhelm/nova:master-ubuntu_bionic
    nova_cell_setup: docker.io/openstackhelm/nova:master-ubuntu_bionic
    nova_cell_setup_init: docker.io/openstackhelm/heat:master-ubuntu_bionic
    nova_compute: docker.io/openstackhelm/nova:master-ubuntu_bionic
    nova_compute_ironic: 'docker.io/kolla/ubuntu-source-nova-compute-ironic:master'
    nova_compute_ssh: docker.io/openstackhelm/nova:master-ubuntu_bionic
    nova_conductor: docker.io/openstackhelm/nova:master-ubuntu_bionic
    nova_consoleauth: docker.io/openstackhelm/nova:master-ubuntu_bionic
    nova_db_sync: docker.io/openstackhelm/nova:master-ubuntu_bionic
    nova_novncproxy: docker.io/openstackhelm/nova:master-ubuntu_bionic
    nova_novncproxy_assets: 'docker.io/kolla/ubuntu-source-nova-novncproxy:master'
    nova_placement: docker.io/openstackhelm/nova:master-ubuntu_bionic
    nova_scheduler: docker.io/openstackhelm/nova:master-ubuntu_bionic
    nova_spiceproxy: docker.io/openstackhelm/nova:master-ubuntu_bionic
    nova_spiceproxy_assets: 'docker.io/kolla/ubuntu-source-nova-spicehtml5proxy:master'
