---
- name: Prepare hosts
  hosts:
    - k8s_contr
    - k8s_minion
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: "Install private key on k8s_contr"
      copy:
        src: /home/ubuntu/.ssh/id_rsa_ansible
        dest: /home/ubuntu/.ssh/id_rsa
        mode: 0600
        group: ubuntu
        owner: ubuntu
      delegate_to: "{{item}}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"

    - name: "Install public key on all hosts"
      copy:
        src: /home/ubuntu/.ssh/id_rsa_ansible.pub
        dest: /home/ubuntu/.ssh/id_rsa.pub
        mode: 0600
        group: ubuntu
        owner: ubuntu
      run_once: False

    - name: "Install public key on k8s_minion"
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa_ansible.pub') }}"
      run_once: False
      delegate_to: "{{item}}"
      delegate_facts: True
      loop: "{{groups['k8s_minion']}}"

    - name: "Install public key on k8s_contr"
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa_ansible.pub') }}"
      run_once: False
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_contr'] }}"

    - name: "Accept traffic on minions to k8s_contr"
      iptables:
        chain: INPUT
        protocol: tcp
        source: "{{ groups['k8s_contr'] | join(',') }}"
        destination_port: 22
        jump: ACCEPT
        action: insert
      run_once: True
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_minion'] }}"
