---
- name: Prepare hosts
  hosts:
    - k8s_contr
    - k8s_minion
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: "Accept traffic on minions to k8s_contr"
      iptables:
        chain: INPUT
        protocol: tcp
        source: "{{ groups['k8s_contr'] | join(',') }}"
        destination_port: '22'
        jump: ACCEPT
        action: insert
      run_once: True
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['k8s_minion'] }}"
