---
- name: Get VMs
  hosts: localhost
  gather_facts: False
  tags:
    - get_servers
  tasks:
    - name: display contr hosts
      debug:
        msg: "{{ airship_hosts['airship_contr'] }}"

    - name: display minions hosts
      debug:
        msg: "{{ airship_hosts['airship_minion'] }}"

    - name: "Getting info about airship_contr if exist"
      os_server_facts:
        auth:
          auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
          username: "{{ lookup('env', 'OS_USERNAME') }}"
          password: "{{ lookup('env', 'OS_PASSWORD') }}"
          project_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
          user_domain_name: "{{ lookup('env', 'OS_USER_DOMAIN_NAME') }}"
          project_domain_name: "{{ lookup('env', 'OS_PROJECT_DOMAIN_NAME') }}"
        region_name: "{{ lookup('env', 'OS_REGION_NAME') }}"
        server: "{{ server_name }}"
      with_items: "{{ airship_hosts['airship_contr'] }}"
      loop_control:
        loop_var: server_name
      register: airship_contr_result

    - name: display contr hosts
      debug:
        var: airship_contr_result

    - when: airship_contr_result.results[0].ansible_facts.openstack_servers != []
      name: Add contr into inventory
      add_host:
         name: "{{ item.public_v4 }}"
         group: airship_contr
      with_items: "{{ airship_contr_result.results[0].ansible_facts.openstack_servers }}"

    - name: "Getting info about airship_minion if exist"
      os_server_facts:
        auth:
          auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
          username: "{{ lookup('env', 'OS_USERNAME') }}"
          password: "{{ lookup('env', 'OS_PASSWORD') }}"
          project_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
          user_domain_name: "{{ lookup('env', 'OS_USER_DOMAIN_NAME') }}"
          project_domain_name: "{{ lookup('env', 'OS_PROJECT_DOMAIN_NAME') }}"
        region_name: "{{ lookup('env', 'OS_REGION_NAME') }}"
        server: "{{ server_name }}"
      with_items: "{{ airship_hosts['airship_minion'] }}"
      loop_control:
        loop_var: server_name
      register: airship_minion_result

    - name: display minion hosts
      debug:
        var: airship_minion_result

    - when: airship_minion_result.results[0].ansible_facts.openstack_servers != []
      name: Add minions into inventory
      add_host:
         name: "{{ item.public_v4 }}"
         group: airship_minion
      with_items: "{{ airship_minion_result.results[1].ansible_facts.openstack_servers }}"
