---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: msite1-rabbitmq-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: openstack-rabbitmq-global
    actions:
      - method: delete
        path: .values.labels.prometheus_rabbitmq_exporter
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  namespace: msite1
  release: msite1-rabbitmq
  chart_name: msite1-rabbitmq
  wait:
    timeout: 300
    labels:
      release_group: airship-msite1-rabbitmq
    resources:
      - type: statefulset
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-msite1-rabbitmq
  test:
    enabled: false
  values:
    pod:
      replicas:
        server: 1
    monitoring:
      prometheus:
        enabled: false
...
