---
- name:
  hosts: localhost
  tasks:
    - name: Set k8s_hosts as fact
      set_fact:
        k8s_hosts:
          k8s_contr:
            - "{{ lookup('env', 'CONTR_NAME') if lookup('env', 'CONTR_NAME') != '' else 'bob_contr' }}"
          k8s_minion:
            # If you need more minion nodes, just add same entry
            - "{{ lookup('env', 'MINION_1_NAME') if lookup('env', 'MINION_1_NAME') != '' else 'stevard_minion'  }}"
            - "{{ lookup('env', 'MINION_2_NAME') if lookup('env', 'MINION_2_NAME') != '' else 'kevin_minion'  }}"
        contr_flavor: b2-60
        contr_image: "Ubuntu 16.04"
        contr_key_name: ansible_key
        contr_net_name: Ext-Net
        minion_flavor: b2-60
        minion_image: "Ubuntu 16.04"
        minion_net_name: Ext-Net
        # Name of the docker registry that later ansible will pull images
        repo_name: docker.io
        openstack_keypair_name: "{{ lookup('env', 'OPENSTACK_KEYPAIR_NAME') if lookup('env', 'OPENSTACK_KEYPAIR_NAME') != '' else 'ansible_key' }}"
        ansible_ssh_keyname: "{{ lookup('env', 'ANSIBLE_SSH_KEYNAME') if lookup('env', 'ANSIBLE_SSH_KEYNAME') != '' else 'id_rsa_ansible'  }}"
  tags:
    - local_inventory

- name: Add ssh key if not present
  hosts: localhost
  remote_user: ubuntu
  gather_facts: False
  roles:
    - ssh_keys
  tags:
    - keypair_add

- name: Create servers
  hosts: localhost
  gather_facts: False
  roles:
    - create_servers
  tags:
    - create_servers

- name: Add VMs to known hosts and install keys on the hosts
  hosts: localhost
  remote_user: ubuntu
  gather_facts: False
  vars:
    ansible_host_key_checking: false
  tags:
    - copy_ssh_keys
  roles:
    - ssh_known_hosts

- name: Configure known_hosts on contr
  hosts:
    - k8s_contr
  remote_user: ubuntu
  gather_facts: False
  vars:
    ansible_host_key_checking: false
  roles:
    - ssh_common_contr
  tags:
    - contr_known_hosts
    - minion_known_hosts

- name: Generate ansible ssh key and add known_hosts
  hosts:
    - k8s_contr
    - k8s_minion
  remote_user: ubuntu
  gather_facts: False
  vars:
    ansible_host_key_checking: false
  tags:
    - ssh_known_hosts
  roles:
    - ssh_common

# Copy
- name: Copy required scripts
  hosts:
    - k8s_contr
    - k8s_minion
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  roles:
    - copy_scripts


# firewall, upgrade packages
- name: Remove, upgrade packages and set iptables
  hosts:
    - k8s_contr
    - k8s_minion
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    setup_minikube: "{{ true if lookup('env', 'SETUP_MINIKUBE') == 'true' else false }}"
  roles:
    - common


- name: Mount etcd dir as RAMDISK
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    etcd_on_ramdisk: "{{ true if lookup('env', 'ETC_ON_RAMDISK') == 'true' else false }}"
  roles:
    - ramdisk_etcd

# deploy_minions
- name: Install required packages for k8s node
  hosts:
    - k8s_minion
  strategy: free
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  roles:
    - deploy_minions

- name: Treasuremap preparation
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  roles:
    - treasuremap_preparations
    - treasuremap_additional_tasks

- name: Execute kubernetes install script
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    setup_minikube: "{{ true if lookup('env', 'SETUP_MINIKUBE') == 'true' else false }}"
  roles:
    - install_k8s_minikube

- name: Execute kubernetes install script
  hosts:
    - k8s_contr
    - k8s_minion
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    setup_minikube: "{{ true if lookup('env', 'SETUP_MINIKUBE') == 'true' else false }}"
  roles:
    - install_k8s_kubernetes

- name: Setup Kubernetes controller
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    setup_minikube: "{{ true if lookup('env', 'SETUP_MINIKUBE') == 'true' else false }}"
  roles:
    - install_k8s_setup_controller

- name: Join minions into the k8s cluster
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  roles:
    - install_k8s_join_node

- name: Set k8s node labels
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    setup_minikube: "{{ true if lookup('env', 'SETUP_MINIKUBE') == 'true' else false }}"
  roles:
    - install_k8s_set_labels

- name: Do post treasuremap things
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  roles:
    - treasuremap_prepare_ucp

- name: Do post treasuremap things
  hosts:
    - k8s_contr
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
  roles:
    - treasuremap_prepare_osh
