---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: keystone-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: keystone-global
      component: keystone
    actions:
      - method: replace
        path: .values.pod
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        api: 1
    conf:
      logging:
        logger_keystone:
          level: DEBUG
spec:
  template:
    spec:
      containers:
      - name: keystone-api
        ports:
        - containerPort: 5000
          name: ks-pub
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 120
          successThreshold: 1
          timeoutSeconds: 60
...
