---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: mynamespace-glance-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: glance-global
      component: glance
    actions:
      - method: merge
        path: .
      - method: replace
        path: .values.pod
      - method: delete
        path: .values.ceph_client
  storagePolicy: cleartext
data:
  chart_name: mynamespace-glance
  release: mynamespace-glance
  namespace: mynamespace
  wait:
    timeout: 300
    labels:
      release_group: airship-mynamespace-glance
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-mynamespace-glance
  test:
    enabled: false
  values:
    bootstrap:
      enabled: false
    pod:
      replicas:
        api: 1
        registry: 1
    storage: pvc
...
