---
- name: Copy kubernetes install script
  hosts: localhost
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    setup_minikube: "{{ true if lookup('env', 'SETUP_MINIKUBE') == 'true' else false }}"
  tasks:
    - when: not setup_minikube
      name: "Copy install-kubernetes script"
      sudo: yes
      sudo_user: ubuntu
      copy:
        src: install-kubernetes.sh
        dest: scripts/
        mode: 0755
        group: ubuntu
        owner: ubuntu
        follow: true
      delegate_to: "{{ item }}"
      delegate_facts: True
      loop: "{{ groups['all'] }}"

- name: Execute kubernetes install script
  hosts:
    - k8s_contr
    - k8s_minion
  gather_facts: False
  remote_user: ubuntu
  become: True
  vars:
    ansible_host_key_checking: false
    setup_minikube: "{{ true if lookup('env', 'SETUP_MINIKUBE') == 'true' else false }}"
  tasks:
    # FIXME: add SETUP_MINIKUBE
    - when: setup_minikube
      name: 010-deploy-k8s.sh
      sudo: yes
      sudo_user: ubuntu
      shell: |
        cd treasuremap && \
        ./tools/deployment/airskiff/developer/010-deploy-k8s.sh 2>&1 | tee -a /home/ubuntu/logs
      ignore_errors: true
      run_once: true

    - when: not setup_minikube
      name: Check if kubeadm is not installed
      shell: |
        dpkg -l | grep -qv kubeadm
      register: kubeadm_status
      ignore_errors: true

    - when: not setup_minikube and kubeadm_status.rc == 0
      name: Install kubernetes packages
      sudo: yes
      sudo_user: ubuntu
      shell: |
        bash -x scripts/install-kubernetes.sh 2>&1 | tee -a /home/ubuntu/logs
      ignore_errors: false
