---
- name: Join k8s host into the cluster
  shell: |
    bash -x scripts/join-node.sh "{{ item }}" 2>&1 | tee -a "logs/cluster-logs-{{ ansible_nodename }}-{{ namespace }}"
  with_items: "{{ groups['k8s_minion'] }}"
